/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TrainerProfile, Post, Short, CommunityPost, CoachingQuestion, UserRole } from "./types";

export const START_TRAINERS: TrainerProfile[] = [
  {
    id: "alex_strength",
    name: "Coach Alexander",
    email: "alexander@leer.sports",
    avatar: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=300&auto=format&fit=crop",
    bio: "Ex-Olympic Weightlifting Coach. Specializing in maximum strength, neural adaptation, and professional athletic performance.",
    specialty: "Strength & Conditioning",
    country: "United States",
    languages: ["English", "Spanish"],
    rating: 4.95,
    subscribersCount: 312,
    monthlyPrice: 49,
    verified: true,
    verificationStatus: "verified",
    certificates: [
      { name: "USA Weightlifting National Coach (Level 3)", url: "#", date: "2021-04" },
      { name: "CSCS - Certified Strength and Conditioning Specialist", url: "#", date: "2019-11" },
    ],
    revenue: {
      total: 18720,
      subscriptions: 15288,
      tips: 3432,
      platformCut: 3744,
      trainerEarnings: 14976,
      history: [
        { month: "Jan", amount: 2400 },
        { month: "Feb", amount: 3100 },
        { month: "Mar", amount: 3900 },
        { month: "Apr", amount: 4200 },
        { month: "May", amount: 5120 },
      ],
    },
    subscribers: [
      { id: "user_1", name: "David Chen", email: "david@gmail.com", activeSince: "2026-01-15", plan: "Standard Sub ($49)" },
      { id: "user_2", name: "Marcus Vance", email: "marcus@vance.fit", activeSince: "2026-03-22", plan: "Standard Sub ($49)" },
      { id: "user_3", name: "Sarah Jenkins", email: "sarah@gmail.com", activeSince: "2026-05-01", plan: "Standard Sub ($49)" },
    ],
  },
  {
    id: "elena_mobility",
    name: "Elena Rostova",
    email: "elena@leer.sports",
    avatar: "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=300&auto=format&fit=crop",
    bio: "Transforming posture and athletic joint integrity. Elite kinetic movement coach for corporate executives and professional performers.",
    specialty: "Posture, Mobility & Pilates",
    country: "Germany",
    languages: ["English", "German", "Russian"],
    rating: 4.89,
    subscribersCount: 245,
    monthlyPrice: 39,
    verified: true,
    verificationStatus: "verified",
    certificates: [
      { name: "Polestar Pilates Practitioner Certification", url: "#", date: "2020-08" },
      { name: "Frcms - Functional Range Conditioning Specialist", url: "#", date: "2022-02" },
    ],
    revenue: {
      total: 12500,
      subscriptions: 9555,
      tips: 2945,
      platformCut: 2500,
      trainerEarnings: 10000,
      history: [
        { month: "Jan", amount: 1800 },
        { month: "Feb", amount: 2100 },
        { month: "Mar", amount: 2500 },
        { month: "Apr", amount: 2900 },
        { month: "May", amount: 3200 },
      ],
    },
    subscribers: [
      { id: "user_1", name: "David Chen", email: "david@gmail.com", activeSince: "2026-02-10", plan: "Mobility Elite ($39)" },
    ],
  },
  {
    id: "marcus_hypertrophy",
    name: "Dr. Marcus Vance",
    email: "marcus@leer.sports",
    avatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80&w=300&auto=format&fit=crop",
    bio: "MD, DPT (Doctor of Physical Therapy). Science-backed evidence-based hypertrophy protocols designed to construct dense lean tissue without joint compromise.",
    specialty: "Hypertrophy & Physical Therapy",
    country: "United Kingdom",
    languages: ["English", "French"],
    rating: 4.98,
    subscribersCount: 450,
    monthlyPrice: 59,
    verified: true,
    verificationStatus: "verified",
    certificates: [
      { name: "Doctor of Physical Therapy (DPT)", url: "#", date: "2018-05" },
      { name: "Board Certified Orthopedic Specialist (OCS)", url: "#", date: "2020-10" },
    ],
    revenue: {
      total: 32000,
      subscriptions: 26550,
      tips: 5450,
      platformCut: 6400,
      trainerEarnings: 25600,
      history: [
        { month: "Jan", amount: 4200 },
        { month: "Feb", amount: 5100 },
        { month: "Mar", amount: 6200 },
        { month: "Apr", amount: 7900 },
        { month: "May", amount: 8600 },
      ],
    },
    subscribers: [],
  },
];

export const START_POSTS: Post[] = [
  {
    id: "post_1",
    trainerId: "alex_strength",
    trainerName: "Coach Alexander",
    trainerAvatar: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=300&auto=format&fit=crop",
    title: "The Ultimate Guide to Lat-Recruitment in Snatch Turnovers",
    content: "The snatch is won or lost in the turnover. Most lifters rely purely on arm pull, leaking force. To maximize neural adaptation, you must engage the latissimus dorsi early in the second pull, keeping the bar swept tight to the hip. Try this cue on your next heavy pull: 'Squeeze oranges in your armpits as the bar passes your knees.' Let me know your thoughts in the comments below!",
    mediaType: "image",
    mediaUrls: ["https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=800&auto=format&fit=crop"],
    type: "public",
    likesCount: 142,
    viewsCount: 1845,
    date: "2026-06-28T14:30:00Z",
    originalLanguage: "English",
    translations: {},
    comments: [
      {
        id: "c1",
        userName: "Marcus",
        userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=100&auto=format&fit=crop",
        text: "That orange cue completely solved my bar-looping issue today. Insane difference!",
        date: "2026-06-28T15:12:00Z",
      },
      {
        id: "c2",
        userName: "Sophia",
        userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100&auto=format&fit=crop",
        text: "Does this apply to clean turnovers as well, or is the latency too short?",
        date: "2026-06-28T16:05:00Z",
      },
    ],
  },
  {
    id: "post_2",
    trainerId: "alex_strength",
    trainerName: "Coach Alexander",
    trainerAvatar: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=300&auto=format&fit=crop",
    title: "Premium Protocol: Weekly Olympic Strength Peaking Block (Weeks 1-4)",
    content: "Welcome subscribers! Here is the detailed weekly block for building absolute strength overhead and stabilizing the shoulder capsule under maximum loads. This features the specific wave-loading formulas for squats, jerks, and accessory pull-throughs that our national-level weightlifters utilize. Access the PDF spreadsheet and exercise tutorial videos attached to this premium locker.",
    mediaType: "image",
    mediaUrls: ["https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?q=80&w=800&auto=format&fit=crop"],
    type: "premium",
    likesCount: 54,
    viewsCount: 312,
    date: "2026-06-27T08:00:00Z",
    originalLanguage: "English",
    translations: {},
    comments: [
      {
        id: "c3",
        userName: "David Chen",
        userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100&auto=format&fit=crop",
        text: "Already on Week 2, squats are feeling lighter than ever. The wave sequence is elite.",
        date: "2026-06-27T10:45:00Z",
      },
    ],
  },
  {
    id: "post_3",
    trainerId: "elena_mobility",
    trainerName: "Elena Rostova",
    trainerAvatar: "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=300&auto=format&fit=crop",
    title: "Decompressing the Lumbar Spine after Heavy Quadrupedal Loading",
    content: "If you are lifting heavy or sitting for 8+ hours a day, your lumbar spine undergoes continuous axial compression. Standard static hamstring stretches do not address the deep posterior fascial network or the psoas major. Use this progressive Active Decompression flow to instantly relieve pelvic tension. Perform each movement for 90 seconds, focusing on diaphragmatic expansion.",
    mediaType: "image",
    mediaUrls: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop"],
    type: "public",
    likesCount: 98,
    viewsCount: 1120,
    date: "2026-06-29T11:00:00Z",
    originalLanguage: "English",
    translations: {},
    comments: [],
  },
  {
    id: "post_4",
    trainerId: "marcus_hypertrophy",
    trainerName: "Dr. Marcus Vance",
    trainerAvatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80&w=300&auto=format&fit=crop",
    title: "Premium: Science-Backed Tension Distribution - Shoulder Growth Without Joint Strain",
    content: "Many lifters sacrifice their AC joints and rotator cuffs in pursuit of wider deltoids. This premium protocol breaks down mechanical tension vs active damage. You will receive custom lateral raise modifications, high-frequency volume equations, and specific scapular plane alignment guidelines designed to maximize lateral head stimulation while leaving your ligaments completely tension-free.",
    mediaType: "image",
    mediaUrls: ["https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=800&auto=format&fit=crop"],
    type: "premium",
    likesCount: 187,
    viewsCount: 921,
    date: "2026-06-25T09:15:00Z",
    originalLanguage: "English",
    translations: {},
    comments: [],
  },
];

export const START_SHORTS: Short[] = [
  {
    id: "short_1",
    trainerId: "alex_strength",
    trainerName: "Coach Alexander",
    trainerAvatar: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=300&auto=format&fit=crop",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-preparing-for-weightlifting-training-in-gym-4886-large.mp4",
    description: "Stop pulling with your arms! Use this simple latch cue for instant snatch power increase 🏋️‍♂️💪 #olympicweightlifting #strength #coaching #shorts",
    likesCount: 1254,
    commentsCount: 88,
    sharesCount: 342,
    isLiked: false,
    isFollowed: false,
    isSubscribed: false,
  },
  {
    id: "short_2",
    trainerId: "elena_mobility",
    trainerName: "Elena Rostova",
    trainerAvatar: "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=300&auto=format&fit=crop",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-young-woman-doing-stretching-exercises-on-a-mat-41584-large.mp4",
    description: "Instantly decompress your lower back! Perform this 2-minute flow after your squats or desk sessions 🧘‍♀️✨ #mobility #backpain #pilates #recovery",
    likesCount: 3105,
    commentsCount: 204,
    sharesCount: 1243,
    isLiked: false,
    isFollowed: false,
    isSubscribed: false,
  },
  {
    id: "short_3",
    trainerId: "marcus_hypertrophy",
    trainerName: "Dr. Marcus Vance",
    trainerAvatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80&w=300&auto=format&fit=crop",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-athletic-man-lifting-barbell-in-gym-41577-large.mp4",
    description: "Is your shoulder press causing AC joint impingement? Make this 15-degree elbow adjustment immediately! 🔬🔥 #hypertrophy #physiotherapy #fitscience",
    likesCount: 8432,
    commentsCount: 542,
    sharesCount: 2901,
    isLiked: false,
    isFollowed: false,
    isSubscribed: false,
  },
];

export const START_COMMUNITY: CommunityPost[] = [
  {
    id: "comm_1",
    userId: "trainee_david",
    userName: "David Chen",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100&auto=format&fit=crop",
    userRole: UserRole.TRAINEE,
    type: "question",
    title: "Need feedback on squat hip-shift at heavy loads",
    content: "Whenever I cross 85% of my 1RM squat, I experience a subtle but noticeable hip shift to the right at the initiation of the ascent. It doesn't hurt, but I want to correct it before increasing weight. Has anyone resolved a similar structural imbalance, and which core drills helped most?",
    likesCount: 14,
    date: "2026-06-29T16:45:00Z",
    originalLanguage: "English",
    translations: {},
    comments: [
      {
        id: "cc1",
        userName: "Elena Rostova",
        userAvatar: "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=300&auto=format&fit=crop",
        text: "David, this is usually caused by an ankle dorsiflexion asymmetry or a slight glute medius activation delay. Try doing single-leg goblet squats focusing on keeping the pelvis perfectly level in a mirror.",
        date: "2026-06-29T18:22:00Z",
      },
    ],
  },
  {
    id: "comm_2",
    userId: "trainee_sophia",
    userName: "Sophia Miller",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100&auto=format&fit=crop",
    userRole: UserRole.TRAINEE,
    type: "flex",
    title: "Hit a new 1RM Snatch! 65kg at 58kg bodyweight! 🎉",
    content: "After 6 months of absolute dedication to Coach Alexander's mobility and explosive strength blocks, I finally clicked the 65kg mark! The technique felt so smooth and light. Keep showing up, consistency works!",
    mediaUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=500&auto=format&fit=crop",
    likesCount: 42,
    date: "2026-06-28T12:00:00Z",
    originalLanguage: "English",
    translations: {},
    comments: [
      {
        id: "cc2",
        userName: "Coach Alexander",
        userAvatar: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=300&auto=format&fit=crop",
        text: "Incredible lift, Sophia! Your hip extension was absolute perfection. Proud coach moment!",
        date: "2026-06-28T12:45:00Z",
      },
    ],
  },
];

export const START_COACHING: CoachingQuestion[] = [
  {
    id: "coaching_1",
    traineeId: "trainee_david",
    traineeName: "David Chen",
    traineeAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100&auto=format&fit=crop",
    trainerId: "alex_strength",
    trainerName: "Coach Alexander",
    title: "Sticking Point at Bottom of Snatch Pull - Bar Asymmetry",
    text: "Hey Coach! When I perform heavy snatch pulls (above 95kg), I feel my left shoulder dipping slightly as I pass the knees. It causes the bar path to become crooked. I've uploaded my workout video. Could you analyze if my pull initiation is correct, or if my lat activation is unbalanced?",
    status: "replied",
    trainerReplyText: "David, great video submission. Looking at the slow-motion frames, your left hip is actually rising slightly faster than your right during the first pull. This creates an unlevel shoulder plane. To fix this, focus on pushing the floor away with equal pressure through your midfoot. Let's do 3 sets of halting snatch pulls at 80% this week to solidify this position.",
    date: "2026-06-28T09:00:00Z",
    replyDate: "2026-06-28T14:15:00Z",
  },
  {
    id: "coaching_2",
    traineeId: "trainee_david",
    traineeName: "David Chen",
    traineeAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100&auto=format&fit=crop",
    trainerId: "elena_mobility",
    trainerName: "Elena Rostova",
    title: "Hip Pinching During Full Deep Squats",
    text: "Elena, I get a sharp pinching sensation in the front of my left hip crease at the very bottom of my deep squats. Is this a femur-acetabulum alignment issue, or simply tight hip flexors? What daily releases should I implement?",
    status: "pending",
    date: "2026-06-29T21:00:00Z",
  },
];
